import { ApolloProvider, ThemeProvider } from '@/app/providers';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';
import { Footer, Header } from '@/components/features';
import { Toaster } from '@/components/ui';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html className="h-full" lang="en" suppressHydrationWarning>
			<body className="h-full">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<>
						<ApolloProvider>
							<div className="wrapper">
								<Header />

								<main className="flex-auto">{children}</main>

								<Footer />
							</div>
						</ApolloProvider>
						<Toaster />
					</>
				</ThemeProvider>
			</body>
		</html>
	);
}
