import { SidebarProvider, Toaster } from '@/components/ui';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import {
	ApolloProvider,
	ReactQueryProvider,
	ThemeProvider,
} from './_providers';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html className="h-full" lang="en" suppressHydrationWarning>
			<body className="h-full">
				<ReactQueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<ApolloProvider>
							<>
								<SidebarProvider
									style={{
										['--sidebar-width' as string]: '20rem',
									}}
								>
									{children}
								</SidebarProvider>

								<Toaster />
							</>
						</ApolloProvider>
					</ThemeProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
